---
- name: Add Docker repo key
  apt_key:
    url: https://apt.dockerproject.org/gpg

- name: Add Docker repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    update_cache: yes

- name: Add Tmux repository
  apt_repository:
    repo: 'ppa:pi-rho/dev'
    update_cache: yes

- name: Update the system and the kernel as well
  apt:
    upgrade: dist

- name: Install base packages
  apt:
    name: "{{ item }}"
  with_items: "{{ packages }}"

- user:
    name: '{{ user }}'
    shell: /usr/bin/zsh
    groups: sudo,docker
    append: yes
